spring.application.name=spring_boot
server.port=8081
# Disable database auto-configuration for testing purposes
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
